### ISSUE TITLE
Investigate PHP support

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [budgielang/budgie#102]
Can PHP be reasonably supported?

**Comment by JoshuaKGoldberg** [comment]
Alas, I don't believe it is. PHP arrays exhibit [write-on-copy behavior](https://stackoverflow.com/questions/40272348/php-array-element-assignment-for-readonly-is-value-copied). That is different from the pass-by-reference behavior used in other supported languages. Darn.

Here's an end-to-end test that would be failing in #666 if the CircleCI machine could run it:

```
> budgie@0.3.27 test:end-to-end C:\Code\budgie
> mocha test/end-to-end.js --timeout 10000 "--language=PHP" "--accept" "--include=Graphs"



  test/end-to-end
    Graphs
      1) PHP


  0 passing (121ms)
  1 failing

  1) test/end-to-end
       Graphs
         PHP:

      AssertionError: expected [ Array(7) ] to deeply equal [ Array(12) ]
      + expected - actual

         "root borders banana"
         "apple borders red"
         "apple borders yellow"
         "banana borders yellow"
      +  "root"
      +  "apple"
      +  "red"
      +  "yellow"
      +  "banana"
         "Hello, world!"
         ""
       ]

      at C:\Code\budgie\test\OutputTests.js:90:54
      at step (test\OutputTests.js:33:23)
      at Object.next (test\OutputTests.js:14:53)
      at fulfilled (test\OutputTests.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:88:5)
```
